required = ["github.com/onsi/ginkgo/ginkgo"]

[[constraint]]
  name = "github.com/aliyun/aliyun-oss-go-sdk"
  version = "1.9.2"

[[constraint]]
  name = "github.com/aliyun/alibaba-cloud-sdk-go"
  version = "1.60.132"
  source = "github.com/aliyun/alibaba-cloud-sdk-go"

[[constraint]]
  name = "github.com/alibabacloud-go/tea-rpc"
  version = "v1.2.0"
  source = "github.com/alibabacloud-go/tea-rpc"

[[constraint]]
  name = "github.com/aliyun/credentials-go"
  version = "v1.1.2"
  source = "github.com/aliyun/credentials-go"

[[constraint]]
  name = "github.com/alibabacloud-go/tea-utils"
  version = "v1.4.5"
  source = "github.com/alibabacloud-go/tea-utils"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry/bosh-utils"

[[constraint]]
  branch = "master"
  name = "github.com/cppforlife/bosh-cpi-go"
#   source = "github.com/aliyun/bosh-cpi-go"

[[constraint]]
  name = "github.com/google/uuid"
  version = "0.2.0"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
